using MriReconstructionToolbox
using GeometricMedicalPhantoms
using Statistics
using FFTW
using Test
using PyCall
using MRIReco
using LinearAlgebra
using Random

include("../src/ComparisonHarness.jl")
using .ComparisonHarness

sigpy = pyimport("sigpy")
sp_mri = pyimport("sigpy.mri")


function compute_nrmse(x::AbstractArray, xref::AbstractArray)
    return norm(x[:] .- xref[:]) / norm(xref[:])
end

function write_cfl(filename, data)
    open(filename*".hdr", "w") do f
        println(f, "# Dimensions")
        dims = collect(size(data))
        while length(dims) < 16
            push!(dims, 1)
        end
        println(f, join(dims, " "))
    end
    open(filename*".cfl", "w") do f
        write(f, ComplexF32.(data))
    end
end

function read_cfl(filename)
    dims = Int[]
    open(filename*".hdr", "r") do f
        for line in eachline(f)
            if !startswith(line, "#") && !isempty(strip(line))
                try
                    dims = parse.(Int, split(line))
                    break
                catch
                end
            end
        end
    end
    while length(dims) > 0 && dims[end] == 1
        pop!(dims)
    end
    if length(dims) == 0; push!(dims, 1); end
    data = Array{ComplexF32}(undef, Tuple(dims))
    open(filename*".cfl", "r") do f
        read!(f, data)
    end
    return data
end

@testset "Reconstruction Benchmark" begin
    # Base setup
    N = 128
    Nc = 8
    
    # Generate data
    img_1c, kspace_1c, _ = ComparisonHarness.generate_multicoil_brain(N=N, num_coils=1)
    img_mc, kspace_mc, cmap = ComparisonHarness.generate_multicoil_brain(N=N, num_coils=Nc)
    
    @testset "Base Reconstruction (Unregularized)" begin
        @testset "Cartesian Adjoint" begin
            # We want to check Cartesian adjoint
            # For 1-coil, we still have a sensitivity map generated by the harness
            kdata_1c = NamedDimsArray(kspace_1c, (:kx, :ky, :coil))
            smaps_1c = NamedDimsArray(ComparisonHarness.generate_multicoil_brain(N=N, num_coils=1)[3], (:x, :y, :coil))
            acq_1c = CartesianAcquisitionInfo(kdata_1c; is3D=false, sensitivity_maps=smaps_1c, shifted_image_dims=(:x, :y))
            E_1c = MriReconstructionToolbox.get_encoding_operator(acq_1c)
            # Adjoint applies IFFT
            mrt_adj_1c = E_1c' * kdata_1c
            
            # Note: the true img_1c is the phantom
            # Since E_1c applies unnormalized IFFT/FFT in MRT?
            # FFTWOperators in MRT usually scales or not. Let's compute normalized error.
            
            # SigPy Adjoint (1-coil)
            kdata_sp_1c = parent(permutedims(kspace_1c, (3, 2, 1)))
            smaps_sp_1c = parent(permutedims(smaps_1c, (3, 2, 1)))
            S_sp_1c = sp_mri.linop.Sense(smaps_sp_1c, ishape=(N, N))
            sp_adj_1c = S_sp_1c.H(kdata_sp_1c)
            # SigPy returns [y, x], transpose to [x, y]
            sp_adj_1c = permutedims(sp_adj_1c, (2, 1))
            
            # MRT and SigPy might use different FFT scalings (e.g. sqrt(N) vs 1)
            scale = norm(abs.(sp_adj_1c)) / norm(abs.(mrt_adj_1c))
            
            nrmse_1c = compute_nrmse(mrt_adj_1c .* scale, sp_adj_1c)
            @info "MRT vs SigPy Cartesian 1C Adjoint NRMSE: $nrmse_1c"
            
            @test nrmse_1c < 1e-4
            
            # MRT Adjoint (multi-coil)
            kdata_mc = NamedDimsArray(kspace_mc, (:kx, :ky, :coil))
            smaps_mc = NamedDimsArray(cmap, (:x, :y, :coil))
            acq_mc = CartesianAcquisitionInfo(kdata_mc; is3D=false, sensitivity_maps=smaps_mc, shifted_image_dims=(:x, :y))
            E_mc = MriReconstructionToolbox.get_encoding_operator(acq_mc)
            mrt_adj_mc = E_mc' * kdata_mc
            
            # SigPy Adjoint (multi-coil)
            kdata_sp_mc = parent(permutedims(kspace_mc, (3, 2, 1)))
            smaps_sp_mc = parent(permutedims(cmap, (3, 2, 1)))
            S_sp_mc = sp_mri.linop.Sense(smaps_sp_mc, ishape=(N, N))
            sp_adj_mc = permutedims(S_sp_mc.H(kdata_sp_mc), (2, 1))
            
            scale_mc = norm(abs.(sp_adj_mc)) / norm(abs.(mrt_adj_mc))
            nrmse_mc = compute_nrmse(mrt_adj_mc .* scale_mc, sp_adj_mc)
            @info "MRT vs SigPy Cartesian MC Adjoint NRMSE: $nrmse_mc"
            @test nrmse_mc < 1e-4
            
            # MRT Adjoint (undersampled)
            mask = rand(MersenneTwister(42), Bool, N, N)
            kdata_us = NamedDimsArray(kspace_mc[mask, :], (:kxy, :coil))
            acq_us = CartesianAcquisitionInfo(kdata_us; is3D=false, image_size=(N, N), sensitivity_maps=smaps_mc, shifted_image_dims=(:x, :y), subsampling=mask)
            E_us = MriReconstructionToolbox.get_encoding_operator(acq_us)
            mrt_adj_us = E_us' * kdata_us
            
            # SigPy Adjoint (undersampled)
            kspace_sp_us = copy(kspace_mc)
            kspace_sp_us[.!mask, :] .= 0
            kdata_sp_us = parent(permutedims(kspace_sp_us, (3, 2, 1)))
            sp_adj_us = permutedims(S_sp_mc.H(kdata_sp_us), (2, 1))
            
            scale_us = norm(abs.(sp_adj_us)) / norm(abs.(mrt_adj_us))
            nrmse_us = compute_nrmse(mrt_adj_us .* scale_us, sp_adj_us)
            @info "MRT vs SigPy Cartesian US Adjoint NRMSE: $nrmse_us"
            @test nrmse_us < 1e-4
            
            # MRIReco Adjoint (multi-coil fully sampled)
            kdata_mr = reshape(kspace_mc, N, N, 1, Nc, 1, 1)
            acq_mr = AcquisitionData(kdata_mr)
            smaps_mr = reshape(cmap, N, N, 1, Nc)
            recoParams = Dict{Symbol, Any}(:reco => "direct", :reconSize => (N, N), :senseMaps => smaps_mr)
            img_mr_direct = MRIReco.reconstruction(acq_mr, recoParams)[:,:,1,1,:]
            mr_adj_mc = sum(img_mr_direct .* conj.(cmap), dims=3)[:,:,1]
            scale_mr_mc = norm(abs.(mr_adj_mc)) / norm(abs.(mrt_adj_mc))
            nrmse_mr_mc = compute_nrmse(mrt_adj_mc .* scale_mr_mc, mr_adj_mc)
            @info "MRT vs MRIReco Cartesian MC Adjoint NRMSE: $nrmse_mr_mc"
            @test nrmse_mr_mc < 1e-4
            
            # MRIReco Adjoint (undersampled)
            kdata_mr_us = reshape(kspace_sp_us, N, N, 1, Nc, 1, 1)
            acq_mr_us = AcquisitionData(kdata_mr_us)
            img_mr_us_direct = MRIReco.reconstruction(acq_mr_us, recoParams)[:,:,1,1,:]
            mr_adj_us = sum(img_mr_us_direct .* conj.(cmap), dims=3)[:,:,1]
            scale_mr_us = norm(abs.(mr_adj_us)) / norm(abs.(mrt_adj_us))
            nrmse_mr_us = compute_nrmse(mrt_adj_us .* scale_mr_us, mr_adj_us)
            @info "MRT vs MRIReco Cartesian US Adjoint NRMSE: $nrmse_mr_us"
            @test nrmse_mr_us < 1e-4
        end
        
        @testset "CG-SENSE" begin
            # MRT
            method = IterativeReconstruction(regularization=(), algorithm=MriReconstructionToolbox.CGNR(maxit=10, tol=0.0))
            x_mrt = reconstruct(acq_mc, method)
            
            # SigPy
            kdata_sp_mc = parent(permutedims(kspace_mc, (3, 2, 1)))
            smaps_sp_mc = parent(permutedims(cmap, (3, 2, 1)))
            sp_cg = sp_mri.app.SenseRecon(kdata_sp_mc, smaps_sp_mc, max_iter=10, show_pbar=false).run()
            sp_cg = permutedims(sp_cg, (2, 1))
            scale_sp = norm(abs.(sp_cg)) / norm(abs.(x_mrt))
            nrmse_sp = compute_nrmse(x_mrt .* scale_sp, sp_cg)
            @info "MRT vs SigPy CG-SENSE NRMSE: $nrmse_sp"
            @test nrmse_sp < 1e-4
            
            # MRIReco
            kdata_mr = reshape(kspace_mc, N, N, 1, Nc, 1, 1)
            acq_mr = AcquisitionData(kdata_mr)
            smaps_mr = reshape(cmap, N, N, 1, Nc)
            recoParams = Dict{Symbol, Any}(:reco => "multiCoil", :reconSize => (N, N), :senseMaps => smaps_mr, :iterations => 10, :solver => MRIReco.CGNR, :reg => [MRIReco.L2Regularization(0.0)])
            img_mr = MRIReco.reconstruction(acq_mr, recoParams)[:,:,1,1,1]
            scale_mr = norm(abs.(img_mr)) / norm(abs.(x_mrt))
            nrmse_mr = compute_nrmse(x_mrt .* scale_mr, img_mr)
            @info "MRT vs MRIReco CG-SENSE NRMSE: $nrmse_mr"
            @test nrmse_mr < 1e-4
            
            # BART
            write_cfl("kspace_tmp", reshape(kspace_mc, N, N, 1, Nc))
            write_cfl("smaps_tmp", reshape(cmap, N, N, 1, Nc))
            run(setenv(`/project/c_mrrecon/bart_mkl pics -S -i 10 kspace_tmp smaps_tmp out_tmp`, "BART_USE_FFTW_WISDOM"=>"1", "BART_TOOLBOX_PATH"=>"/project/c_mrrecon"))
            bart_cg = read_cfl("out_tmp")[:,:,1]
            scale_bart = norm(abs.(bart_cg)) / norm(abs.(x_mrt))
            nrmse_bart = compute_nrmse(x_mrt .* scale_bart, bart_cg)
            @info "MRT vs BART CG-SENSE NRMSE: $nrmse_bart"
            @test nrmse_bart < 1e-4
        end
    end
end
